use_frameworks!

target 'AFTPhotoScroller_Example' do
  pod 'AFTPhotoScroller', :path => '../'

# target 'AFTPhotoScroller_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase'
#  end
end
